### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by John-Nagle** [iszak/jpeg2000#1]
Looks like this was started, but not finished. How far did it get? Are there plans to do anything more with it? Thanks.

**Comment by iszak** [comment]
Hello, the jp2 container (part 1, annex I) is mostly done but likely not consumable. I'm planning to implement jpxml (part 14) before going onto decoding the code stream. I have created a library for the arithmetic coding which is needed for decoding the code stream, but unable to verify correctness just yet. What use cases are you looking to cover?

**Comment by John-Nagle** [comment]
All I need is JPEG 2000 decode. I'm working on a Second Life viewer, and all their assets are in JPEG 2000. I'm using the crate that calls the C library, but it sometimes segfaults. Hence the desire for an all-Rust solution.

**Comment by iszak** [comment]
Unfortunately the completion of this project is unlikely to meet your deadlines. I'm not sure which JPEG2000 implementation you've tried, but there are a few JPEG 2000 implementations; [openjpeg](https://github.com/uclouvain/openjpeg), [grok](https://github.com/GrokImageCompression/grok), [jasper](https://github.com/jasper-software/jasper) and kakadu (closed source). If you know of any other open source ones let me know.

**Comment by John-Nagle** [comment]
Did not know about "grok". Knew about the others.
