### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by davystrong** [iszak/jpeg2000#3]
Hello, any chance you can add a license to this project?

**Comment by davystrong** [comment]
I was thinking of attempting implement a JPEG 2000 reader, and if this had an open license like MIT or Apache, I would start with it. Though the chances of me actually succeeding are probably slim.

**Comment by iszak** [comment]
I am considering LGPL to ensure any modifications are also released, but usage is permitted. Would this be acceptable in your use case?

**Comment by davystrong** [comment]
Honestly, I'm not a fan copyleft licenses, though it's obviously up to you. I get why they exist - I agree that any work which improves on your original work **with the intention of reading JPEG 2000 images** should be published in the same way. The problem is that (correct me if I'm wrong) **anything** that uses the library must also be open source, with the possible exception of dynamically linked libraries.

**Comment by davystrong** [comment]
That would be perfect, but various places suggest it requires the library to be dynamically linked ([this SO question](https://stackoverflow.com/questions/10130143/gpl-lgpl-and-static-linking), [this SO question](https://softwareengineering.stackexchange.com/questions/47323/can-i-use-an-lgpl-licenced-library-in-my-commercial-app) and, indirectly, [gnu.org](https://www.gnu.org/licenses/why-not-lgpl.en.html)). As I understand it, this is impractical in Rust.

**Comment by iszak** [comment]
You appear to be right, there's some issues around static linking with LGPL, it seems it can be fixed with a linking exception but I'd rather have a unmodified license. Another alternative is the Mozilla Public License, which is also a weak copy left, which does permit static linking without modification. Would this be an acceptable license for yourself?

**Comment by davystrong** [comment]
I saw the Mozilla Public license too. It would be perfect to me, but it is a very weak copy left license, so it depends if that's acceptable to you.

**Comment by iszak** [comment]
This project is now licensed under MPL 2.0
